using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace OrisonFeeAnalysis.Entities.Student
{
    public class dtStudentRegisterOld
    {
        [Key]
        public int AccountID { get; set; }
        public string AccountCode { get; set; }
        public string AccountName { get; set; }
        public string StudentStatus { get; set; }
        public string SubStatus { get; set; }
        public DateTime StartsFrom { get; set; }
        //public string StartsFrom { get; set; }
        public string Sex { get; set; }
        public string Nationality { get; set; }
        public DateTime DateOfBirth { get; set; }
        //public string DateOfBirth { get; set; }
        public string Age { get; set; }
        public string Class { get; set; }
        public string Division { get; set; }
        public string Address1 { get; set; }
        public string PerMobile { get; set; }
        public string FamilyCode { get; set; }
        public string ParentID { get; set; }
        public string ParentCode { get; set; }
        public string ParentName { get; set; }
        public string AcademicYear { get; set; }
        public string ClassDiv { get; set; }
        public string JoiningAcademicYear { get; set; }
        public string Shift { get; set; }
        public string BranchID { get; set; }
        public string SmsNumber { get; set; }
        public string WhatsAppNo { get; set; }
        public string StudyModel { get; set; }
        public string PlaceOFBirth { get; set; }
        public string RollNo { get; set; }
        public string ClNo { get; set; }
        public string PerAddress1 { get; set; }
        public string PerTelOff { get; set; }
        public string PerTel { get; set; }
        public string BusNo { get; set; }
        public string BusPoint { get; set; }
        public string Expr1 { get; set; }
        public string Religion { get; set; }
        public string BusMode { get; set; }
        public string MotherTongue { get; set; }
        public string NameInArabic { get; set; }
        public string OpLanguage1 { get; set; }
        public string OpLanguage2 { get; set; }
        public string PrevSchool { get; set; }
        public string RegisterNo { get; set; }
        public string SportsHouse { get; set; }
        public string ArabNonArab { get; set; }
        public string ReRegistrationStatus { get; set; }
        public string ReRegistrationDate { get; set; }
        public string Mother { get; set; }
        public string MotherMobile { get; set; }
        public string TcDetails { get; set; }
        public string SLanguage { get; set; }
        public string MinistryStatus { get; set; }
        public string Mobile { get; set; }
        public string Location { get; set; }
        public string Remrk { get; set; }
        public string PrevStatus { get; set; }
        public string Email { get; set; }
        public string PerEmail { get; set; }
        public string MotherEmail { get; set; }


        public string ParentType { get; set; }
        public string TelOff { get; set; }
        public string MotherTelOff { get; set; }
        public string PermMobile { get; set; }
        public string PayerMobile { get; set; }
        public string OpDivision { get; set; }
        public string PrevClass { get; set; }
        public string JoiningClass { get; set; }
        public string JoiningDivision { get; set; }
        public string PrevDivision { get; set; }
        public string POBox { get; set; }
        public string Expr2 { get; set; }
        public string BusArea { get; set; }
        public string GoingBusNo { get; set; }
        public string BusTimeIn { get; set; }
        public string YCode { get; set; }
        public string BusTimeOut { get; set; }
        public string TeacherOfTheSubject { get; set; }
        public string Optional { get; set; }
        public string PrevPlace { get; set; }
        public string PrevTcType { get; set; }
        public string TcDate { get; set; }
        public string ApprovalDate { get; set; }
        public string PerMobile2 { get; set; }
        public string StudentType { get; set; }
        public string SecondRelation { get; set; }
        public string MotherHomeTel { get; set; }
        public string MotherProfession { get; set; }
        public string MotherEmail2 { get; set; }
        public string MotherMobile2 { get; set; }
        public string PerEmail2 { get; set; }
        public string PayerRelation { get; set; }
        public string SSection { get; set; }
        public string LeavingDate { get; set; }
        public string MotherNameActual { get; set; }
        public string PdcRemarks { get; set; }
        public string MotherAddressActual { get; set; }
        public string MotherPoBoxActual { get; set; }
        public string MotherProfessionActual { get; set; }
        public string MotherCityActual { get; set; }
        public string MotherCountryActual { get; set; }
        public string MotherOfficeTelActual { get; set; }
        public string MotherHomeTelActual { get; set; }
        public string MotherMobile1Actual { get; set; }
        public string MotherMobile2Actual { get; set; }
        public string MotherEmail1Actual { get; set; }
        public string MotherEmail2Actual { get; set; }
        public string BusStopNo { get; set; }
        public string BusStopNoTo { get; set; }
        public string DropOffPoint { get; set; }
        public string Blocked { get; set; }
        public string MotherWorkingPlaceActual { get; set; }
        public string MotherCompanyActual { get; set; }
        public string RelationContactsActual { get; set; }
        public string PayerProfession { get; set; }
        public string PayerCompany { get; set; }
        public string PayerOfficePhone { get; set; }
        public string PayerHomePhone { get; set; }
        public string PayerMobile2 { get; set; }
        public string PayerEmail { get; set; }
        public string PayerEmail2 { get; set; }
        public string ActivitySchedule { get; set; }
        public string FeeSchedule { get; set; }
        public string TransSchedule { get; set; }
        public string DiscountSchedule { get; set; }
        public string AdmissionSchedule { get; set; }
        public string TranDiscountSchedule { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string FirstNameInArabic { get; set; }
        public string MiddleNameInArabic { get; set; }
        public string LastNameInArabic { get; set; }
        public string PassportNo { get; set; }
        public DateTime? PassportIssueDate { get; set; }
        public DateTime? PassportExpiryDate { get; set; }
        public string PassportIssuePlace { get; set; }
        public string VisaNo { get; set; }
        public DateTime? VisaIssueDate { get; set; }
        public DateTime? VisaExpiryDate { get; set; }
        public string FamilyNo { get; set; }
        public string FamilyCodeIssueDate { get; set; }
        public string FamilyCodeExpiryDate { get; set; }
        public string EmiratesIDNo { get; set; }
        public DateTime? EmiratesIDIssueDate { get; set; }
        public DateTime? EmiratesIDExpiryDate { get; set; }
        public string FatherEmiratesIDNo { get; set; }
        public string MotherEmiratesIDNo { get; set; }
        public string StreetName { get; set; }
        public string Muncipality { get; set; }
        public string ParentNationality { get; set; }
        public string IGCSEStream { get; set; }
        public string StudentFromArab { get; set; }
        public DateTime? AdmissionDate { get; set; }
        public string PlaceOfWork { get; set; }
        public string MotherWorkingPlace { get; set; }
        public string StaffCode { get; set; }
        public string StaffName { get; set; }
        public string SENChild { get; set; }
        public string TransferReason { get; set; }
        public string TransferredSchool { get; set; }
        public DateTime? TransferDate { get; set; }
        public string SpecialNeed { get; set; }
        public DateTime? StudyModelDate { get; set; }
        public string TransportationModel { get; set; }
        public string GroupAllocation { get; set; }
        public string PhotoExist { get; set; }
        public bool? Reregistered { get; set; }
        public bool? DocTc { get; set; }
        public bool? DocBirthCertificate { get; set; }
        public bool? DocPassport { get; set; }
        public bool? DocPhoto { get; set; }
        public bool? DocVaccinationCard { get; set; }
        public bool? SpeakEnglish { get; set; }
        public bool? SpeakEnglishMother { get; set; }
        public bool? MotherSpeakEnglishActual { get; set; }
        public bool? Result { get; set; }
        public bool? EntranceExam { get; set; }
        public bool? PhotoAllowed { get; set; }
        public bool? FeeDiscount { get; set; }
        public bool? TranDiscount { get; set; }
        public bool? DocEmiratesID { get; set; }
        public bool? DocVisa { get; set; }
        public bool? DocSponsorPassport { get; set; }
        public bool? DocSponsorVisa { get; set; }
        public bool? DocReportCard { get; set; }
        public bool? DocMedicalReport { get; set; }
        public bool? DocFamilyBook { get; set; }
        public bool? DocSponsorID { get; set; }
        public bool? IEP { get; set; }
        public byte[] Photo { get; set; }
    }
}
